/**
 * Common UK medication names for autocomplete.
 * Sources: NHS Medicines A-Z, common OTC and prescribed medications.
 * Generic names preferred; brand names included where commonly used.
 * Sorted alphabetically.
 */
export const MEDICATION_NAMES: string[] = [
  // A
  'Aciclovir',
  'Acrivastine',
  'Adalimumab',
  'Alendronic acid',
  'Allopurinol',
  'Alogliptin',
  'Amitriptyline',
  'Amlodipine',
  'Amoxicillin',
  'Anastrozole',
  'Apixaban',
  'Aripiprazole',
  'Aspirin',
  'Atenolol',
  'Atorvastatin',
  'Azathioprine',
  'Azithromycin',

  // B
  'Baclofen',
  'Beclometasone',
  'Bendroflumethiazide',
  'Benzoyl peroxide',
  'Benzydamine',
  'Betahistine',
  'Betamethasone',
  'Bimatoprost',
  'Bisacodyl',
  'Bisoprolol',
  'Brinzolamide',
  'Budesonide',
  'Bumetanide',
  'Buprenorphine',

  // C
  'Calcipotriol',
  'Candesartan',
  'Carbamazepine',
  'Carbimazole',
  'Carbocisteine',
  'Carmellose sodium',
  'Carvedilol',
  'Cefalexin',
  'Cetirizine',
  'Chloramphenicol',
  'Chlorhexidine',
  'Chlorphenamine',
  'Cinnarizine',
  'Ciprofloxacin',
  'Citalopram',
  'Clarithromycin',
  'Clobetasol',
  'Clobetasone',
  'Clonazepam',
  'Clonidine',
  'Clopidogrel',
  'Clotrimazole',
  'Co-amoxiclav',
  'Co-beneldopa',
  'Co-careldopa',
  'Co-codamol',
  'Co-dydramol',
  'Codeine',
  'Colchicine',
  'Colecalciferol',
  'Cyclizine',

  // D
  'Dapagliflozin',
  'Dexamethasone',
  'Diazepam',
  'Diclofenac',
  'Digoxin',
  'Dihydrocodeine',
  'Diltiazem',
  'Diphenhydramine',
  'Dipyridamole',
  'Docusate',
  'Domperidone',
  'Donepezil',
  'Doxazosin',
  'Doxycycline',
  'Duloxetine',

  // E
  'Edoxaban',
  'Empagliflozin',
  'Enalapril',
  'Eplerenone',
  'Erythromycin',
  'Escitalopram',
  'Esomeprazole',
  'Ezetimibe',

  // F
  'Felodipine',
  'Fentanyl',
  'Ferrous fumarate',
  'Ferrous sulfate',
  'Fexofenadine',
  'Finasteride',
  'Flucloxacillin',
  'Fluconazole',
  'Fluoxetine',
  'Fluticasone',
  'Folic acid',
  'Furosemide',
  'Fusidic acid',

  // G
  'Gabapentin',
  'Gaviscon',
  'Gliclazide',
  'Glyceryl trinitrate',

  // H
  'Haloperidol',
  'Hydrocortisone',
  'Hydroxocobalamin',
  'Hydroxychloroquine',
  'Hyoscine butylbromide',
  'Hyoscine hydrobromide',

  // I
  'Ibuprofen',
  'Indapamide',
  'Insulin',
  'Irbesartan',
  'Isosorbide mononitrate',
  'Isotretinoin',

  // K
  'Ketoconazole',

  // L
  'Lactulose',
  'Lamotrigine',
  'Lansoprazole',
  'Latanoprost',
  'Lercanidipine',
  'Letrozole',
  'Levetiracetam',
  'Levothyroxine',
  'Lidocaine',
  'Linagliptin',
  'Lisinopril',
  'Lithium',
  'Loperamide',
  'Loratadine',
  'Lorazepam',
  'Losartan',
  'Lymecycline',

  // M
  'Macrogol',
  'Mebendazole',
  'Mebeverine',
  'Medroxyprogesterone',
  'Melatonin',
  'Memantine',
  'Mesalazine',
  'Metformin',
  'Methadone',
  'Methotrexate',
  'Methylphenidate',
  'Metoclopramide',
  'Metoprolol',
  'Metronidazole',
  'Mirabegron',
  'Mirtazapine',
  'Mometasone',
  'Montelukast',
  'Morphine',

  // N
  'Naproxen',
  'Nefopam',
  'Nicorandil',
  'Nifedipine',
  'Nitrofurantoin',
  'Nortriptyline',
  'Nystatin',

  // O
  'Olanzapine',
  'Omeprazole',
  'Oxybutynin',
  'Oxycodone',

  // P
  'Pantoprazole',
  'Paracetamol',
  'Paroxetine',
  'Peppermint oil',
  'Perindopril',
  'Phenoxymethylpenicillin',
  'Pravastatin',
  'Prednisolone',
  'Pregabalin',
  'Prochlorperazine',
  'Promethazine',
  'Propranolol',
  'Pseudoephedrine',

  // Q
  'Quetiapine',

  // R
  'Ramipril',
  'Ranitidine',
  'Risperidone',
  'Rivaroxaban',
  'Ropinirole',
  'Rosuvastatin',

  // S
  'Salbutamol',
  'Senna',
  'Sertraline',
  'Sildenafil',
  'Simeticone',
  'Simvastatin',
  'Sitagliptin',
  'Sodium valproate',
  'Solifenacin',
  'Sotalol',
  'Spironolactone',
  'Sulfasalazine',
  'Sumatriptan',

  // T
  'Tadalafil',
  'Tamsulosin',
  'Terbinafine',
  'Thiamine',
  'Tibolone',
  'Ticagrelor',
  'Timolol',
  'Tiotropium',
  'Tolterodine',
  'Topiramate',
  'Tramadol',
  'Tranexamic acid',
  'Trastuzumab',
  'Trazodone',
  'Trimethoprim',

  // V
  'Valproic acid',
  'Valsartan',
  'Varenicline',
  'Venlafaxine',
  'Verapamil',
  'Vitamin D',

  // W
  'Warfarin',

  // Z
  'Zolpidem',
  'Zopiclone',

  // Common UK brand names (where people more commonly know the brand)
  'Calpol',
  'Nurofen',
  'Piriton',
  'Clarityn',
  'Sudafed',
  'Gaviscon',
  'Imodium',
  'Buscopan',
  'Canesten',
  'Lemsip',
  'Night Nurse',
  'Day Nurse',
  'Beechams',
  'Benylin',
  'Bonjela',
  'Difflam',
  'Dioralyte',
  'E45',
  'Germoloids',
  'Lacto Calamine',
  'Olbas Oil',
  'Rennie',
  'Savlon',
  'Strepsils',
  'TCP',
  'Vicks',
  'Voltarol',
  'Zovirax',
  'Anadin',
  'Beconase',
  'Corsodyl',
  'Deep Heat',
  'Dulcolax',
  'Fybogel',
  'Piriteze',
  'Senokot',
]
